### ISSUE TITLE
Add a callback for current change on DOMProxy

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/Holoflows-Kit#105]

**Comment by SunriseFox** [comment]
https://github.com/DimensionDev/Maskbook/blob/b466748796ae311d4a95a99d6a373526248cac0a/src/utils/jss/renderInShadowRoot.tsx#L21-L30

We are polling here to detect if an element has been inserted to document...

**Comment by Jack-Works** [comment]
@SunriseFox implemeted
