### ISSUE TITLE
[Discussion] What's the best way to describe Holoflows etc

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/holoflows-kit#11]
**Need put more thoughts here**

Maybe we need to define some terms we created here:

- Flows
- The environment running flows; here, holoflows or other extension etc compatible with holoflows
- The holoflows-kit (this repo) now

**Comment by neruthes** [comment]
`Make Web Browsers For-The-People Again!`

**Comment by neruthes** [comment]
- The `applet` itself may be called `mini program` or `flow`, for working with App Store censorship.
- `Holoflows` is our implementations which are compatible with `Webflows` technological specifications.
- This library, `Holoflows-Kit`, is the backbone in Holoflows, which other developers are encouraged to audit and reuse.

**Comment by Tedko** [comment]
Term `mini program` is now connected to wechat. Let’s avoid this. `Applet` is cool.

**Comment by Tedko** [comment]
I mean `flow` is cool

**Comment by Tedko** [comment]
> * The `applet` itself may be called `mini program` or `flow`, for working with App Store censorship.
> * `Holoflows` is our implementations which are compatible with `Webflows` technological specifications.
> * This library, `Holoflows-Kit`, is the backbone in Holoflows, which other developers are encouraged to audit and reuse.

maybe Change the description of this repo to `Toolkit for mordern Web 3.0 flow development, backbone in Holoflows` ?

**Comment by neruthes** [comment]
> > * The `applet` itself may be called `mini program` or `flow`, for working with App Store censorship.
> > * `Holoflows` is our implementations which are compatible with `Webflows` technological specifications.
> > * This library, `Holoflows-Kit`, is the backbone in Holoflows, which other developers are encouraged to audit and reuse.
> 
> maybe Change the description of this repo to `Toolkit for mordern Web 3.0 flow development, backbone in Holoflows` ?

I would argue that `Web 3.0` is not the term which we really want to compete owning, quoting "I have no idea what would WW3 look like, but I am pretty sure that WW4 will be fought with spears and rocks" from Albert Einstein (reportedly).

Instead, `Webflows` is something we may be interested in. Now domain name `webflows.org` has been in my possession. We may go further with this.

**Comment by Tedko** [comment]
ok. Webflows is good. Get back to this very soon.

**Comment by Tedko** [comment]
> > > * The `applet` itself may be called `mini program` or `flow`, for working with App Store censorship.
> > > * `Holoflows` is our implementations which are compatible with `Webflows` technological specifications.
> > > * This library, `Holoflows-Kit`, is the backbone in Holoflows, which other developers are encouraged to audit and reuse.
> > 
> > 
> > maybe Change the description of this repo to `Toolkit for mordern Web 3.0 flow development, backbone in Holoflows` ?
> 
> I would argue that `Web 3.0` is not the term which we really want to compete owning, quoting "I have no idea what would WW3 look like, but I am pretty sure that WW4 will be fought with spears and rocks" from Albert Einstein (reportedly).
> 
> Instead, `Webflows` is something we may be interested in. Now domain name `webflows.org` has been in my possession. We may go further with this.

@asonmine  go ahead with the domain.
