### ISSUE TITLE
live selector not working on twitter.

### ISSUE THREAD

**Issue by Misaka-0x447f** [DimensionDev/holoflows-kit#17]

**Comment by Jack-Works** [comment]
Do you have an example? What do you mean by "not working"?

**Comment by Misaka-0x447f** [comment]
ok, the thing is, live selector can select the post box on the twitter.com, but MOW useForeach callback never get called. see line 13 of the maskbook file src/social-network-provider/twitter.com/ui/inject.tsx

**Comment by Misaka-0x447f** [comment]
git checkout branch 'feat/twitter' on the maskbook, then go to file ```src/social-network-provider/twitter.com/ui/inject.tsx``` and add a useForeach with console.log, or debugger, whatever, inside. you will noticed that it never run.

**Comment by Misaka-0x447f** [comment]
this is not a bug, it was caused by using both single mode and batch mode.
