### ISSUE TITLE
liveSelector.evaluate does not respect consistentWatchRoot

### ISSUE THREAD

**Issue by SunriseFox** [DimensionDev/Holoflows-Kit#46]
Suppose we have this document:

```html
<div>
  <a class="content">Not me</a> = $0
</div>
<div id="root">
  <a class="content">But me</a> = $1
</div>
```

a `new LiveSelector().querySelector('.content')`, and a `new MutationObserverWatcher(selector, root)`. If we `startWatch()` this, it would match **$0** but not **$1** and never respond to changes.

**Comment by Jack-Works** [comment]
yes, they are two seperate things. work as intended
